### PR TITLE
Merge Kitware Verdict

### PR DESCRIPTION
**Pull request by spyridon97**
The purpose of this PR is to merge https://gitlab.kitware.com/verdict/verdict and https://github.com/sandialabs/verdict.

Applied changes:
1) All files: Use c++ headers, and remove the unused headers and defines
2) v_vector.h: Deleted since it's no longer used because it has been replaced by VerdictVector
3) VerdictVector: length() function has been re-enabled to resolve compiler warnings
4) All files: Code formatting has been fixed to be consistent across the whole repository
5) Metrics files: Make all input coordinates const qualified
6) Metrics files: Fix typos
7) Metrics files: Comment out unused num_nodes parameters
8) Metrics files: delete not implemented functions
9) All files: remove __BORLANDC__ define, since it's no longer used
10) All files: use c++ version of <cmath> functions
11) CMakeLists.txt: Fix CMakePackaging
12) README.md: improve README.md
12) Remove executable mode from files

Additionally, [VerdictDocumentationUpdates.txt](https://github.com/sandialabs/verdict/files/7875187/VerdictDocumentationUpdates.txt) has been compiled which includes all the required changes for the Documentation to be up-to-date with the code.

### CODE REVIEW

**Comment by spyridon97** [comment]
@clintonstimpson Any updates on the PR?

**Comment by spyridon97** [comment]
VerdictDevelopment has been re-added

**Comment by spyridon97** [comment]
Could you also tag with version 1.4.0?

**Comment by corefmark** [comment]
I just added a tag at the merge commit. From: Spiros TsalikisSent: Wednesday, March 2, 2022 10:51 AMTo: sandialabs/verdictCc: corefmark; State changeSubject: Re: [sandialabs/verdict] Merge Kitware Verdict (PR #1) Could you also tag with version 1.4.0?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you modified the open/close state.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com

**Pull request merged**
